apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hellracerx-poi-map-app-dev
  annotations:
    argocd/app-name: hellracerx-poi-map-app-dev
    backstage.io/kubernetes-id: hellracerx-poi-map-app
    backstage.io/kubernetes-namespace: hellracerx
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-lab/hellracerx-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/dev-pipelines/ns/hellracerx/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/k8s/ns/hellracerx/deployments/hellracerx-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-m9x67.dusy.p1.openshiftapps.com/#https://github.com/rhdh23-lab/hellracerx-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://hellracerx-poi-map-app-hellracerx.apps.rosa-m9x67.dusy.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hellracerx"
  system: workshop-system-hellracerx
  consumesApis:
    - gateway-api-hellracerx
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hellracerx
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hellracerx"
